# Generated by Django 3.1.8 on 2022-07-03 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiv1', '0003_auto_20220703_0828'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pdfdocument',
            old_name='catefory',
            new_name='category',
        ),
    ]
