# Generated by Django 3.1.8 on 2022-06-19 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiv1', '0002_auto_20220619_1607'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='books',
            new_name='book',
        ),
    ]
